version: "3"
services:
  dockertest:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "6590:6579"
    container_name: docker-test
    depends_on:
      - mysql
    networks:
      - stop-server-bridge
  mysql:
    container_name: mysql-8
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
    volumes:
      - /root/data/mysql:/var/lib/mysql
    networks:
      - stop-server-bridge
networks:
  stop-server-bridge: